package ca.gc.inspection.scoop.postoptionsdialog;

import android.support.annotation.NonNull;
import android.util.Log;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import java.util.HashMap;
import java.util.Map;

import ca.gc.inspection.scoop.Config;
import ca.gc.inspection.scoop.util.NetworkUtils;

import static com.google.gson.internal.$Gson$Preconditions.checkNotNull;


/**
 * PostOptionsDialogInteractor used by the Presenter to create POST request and store data into the Model(database/server)
 */
class PostOptionsDialogInteractor {

    private PostOptionsDialogPresenter mPresenter;

    public PostOptionsDialogInteractor(@NonNull PostOptionsDialogPresenter presenter) {
        mPresenter = checkNotNull(presenter);
    }

    /**
     * Verifies save post information generated by user attempting to save a post
     * - Response contains error message if save failed
     * - Response contains success message if save successful
     * @param network Singleton utility to add string request to global application request queue
     * @param activityid ID of the activity in which the user is click on
     * @param userid ID of the user
     */

    public void savePost(NetworkUtils network, final String activityid, final String userid) {

        Log.i("MIDDLE-TIER CHECK", "sending data to save post table");
        String url = Config.baseIP + "post/save-post";

        StringRequest postRequest = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                Log.i("RESPONSE", response);
                mPresenter.setSaveResponseMessage(response);
            }
        }, new Response.ErrorListener()
                {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        // error
                        Log.d("Error.Response", String.valueOf(error));
                    }
                }
        ){
            @Override
            protected Map<String, String> getParams()
            {
                Map<String, String>  params = new HashMap<>();
                params.put("activityid", activityid);
                params.put("userid", userid); // Post test user

                return params;
            }

            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                // inserting the token into the response header that will be sent to the server
                Map<String, String> header = new HashMap<>();
                header.put("authorization", Config.token);
                return header;
            }
        };
        network.addToRequestQueue(postRequest);
    }
}
